[project]
name = "ui-testing-selenium"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "allure-pytest>=2.15.0",
    "pytest>=8.4.2",
    "selenium>=4.36.0",
]
